# Test related func

In [1]:
# test reader
from Load import OSMBuildingReader

cada_reader = OSMBuildingReader(encoding="utf-8")
cada_path = "./data/Cadastre_buildings.shp"
cada_reader.read_osm_buildings(cada_path)
cada_reader.print_info()

cada_reader.split_multipolygons()
cada_reader.add_centroid_column()
gdf = cada_reader.clean_data
gdf

INFO:Load.shp_reader:正在读取shapefile: data/Cadastre_buildings.shp
INFO:Load.shp_reader:成功读取 4905 个要素
INFO:Load.shp_reader:原始坐标系: EPSG:32618
INFO:Load.shp_reader:转换坐标系: EPSG:32618 -> EPSG:3857
INFO:Load.shp_reader:坐标系转换完成
WARNING:Load.shp_reader:发现 26 个无效几何对象
INFO:Load.shp_reader:移除无效几何对象后，剩余 4879 个要素
WARNING:Load.shp_reader:发现 26 个无效几何对象
INFO:Load.shp_reader:移除无效几何对象后，剩余 4879 个要素
INFO:Load.shp_reader:分割multipolygons后，共有 5351 个要素
INFO:Load.shp_reader:已添加质心列

==================================================
Shapefile info
==================================================
文件路径: data/Cadastre_buildings.shp
要素数量: 4905
列数: 3
列名: ['BuildingId', 'height', 'geometry']
原始坐标系: EPSG:32618
当前坐标系: EPSG:3857
边界框: [-8416068.889547948, 695887.7617808486, -8413363.225300174, 697174.1225201517]
几何类型: {'Polygon': 4561, 'MultiPolygon': 344}
空几何数量: 0
无效几何数量: 26
==================================================

,BuildingId,height,geometry,ori_id,centroid
0,110700500120000,10.0,"POLYGON ((-8414873.538 696408.792, -8414871.67...",110700500120000,POINT (-8414880.114 696406.627)
1,110903600190000,13.0,"POLYGON ((-8415896.375 696427.477, -8415896.97...",110903600190000,POINT (-8415890.427 696432.566)
2,111103800030000,17.0,"POLYGON ((-8415918.661 697032.037, -8415918.94...",111103800030000,POINT (-8415919.432 697048.293)
3,110500300270000,14.0,"POLYGON ((-8413918.398 695996.547, -8413918.30...",110500300270000,POINT (-8413920.912 695993.526)
4,110505200240000,20.0,"POLYGON ((-8413990.066 696473.458, -8413993.32...",110505200240000,POINT (-8413993.085 696485.465)
...,...,...,...,...,...
4901,110807500270000,11.0,"POLYGON ((-8415313.626 695932.177, -8415325.68...",110807500270000,POINT (-8415319.961 695940.346)
4902,110500400080000,12.0,"POLYGON ((-8414151.762 695957.224, -8414154.78...",110500400080000,POINT (-8414153.398 695962.394)
4903,110503300130000,16.0,"POLYGON ((-8413574.983 696198.436, -8413572.37...",110503300130000,POINT (-8413577.268 696199.79)
4904,111102300060000,17.0,"POLYGON ((-8415560.87 697056.44, -8415561.114 ...",111102300060000,POINT (-8415564.107 697063.954)
4904,111102300060000,17.0,"POLYGON ((-8415568.403 697059.356, -8415568.84...",111102300060000,POINT (-8415568.776 697057.31)


## Test Cluster

In [2]:
from Cluster import mask2geo
masks_path = "./Cluster/mask_res/cada_masks_2048_2048.pkl"

clustered_gdf = mask2geo(gdf, masks_path=masks_path)
clustered_gdf

INFO:root:mask have been converted to single, and shape is (2048, 2048)
INFO:root:cluster id assigning done!
INFO:root:Loaded 297 masks
INFO:root:Added cluster IDs to 5351 polygons
INFO:root:Polygon cluster distribution:
 0       687232
1      1360635
2         9869
3        30228
4         8271
        ...
293       9243
294       8156
295       5380
296      12292
297       8084
Name: count, Length: 296, dtype: int64
INFO:root:Dealing with Multiple Polygons ...
INFO:root:finding 343 multipolygons
INFO:root:All multipolygons have been assigned with same cluster id!

,BuildingId,height,geometry,ori_id,centroid,pixel,cluster_id,all_ids
0,110700500120000,10.0,"POLYGON ((-8414873.538 696408.792, -8414871.67...",110700500120000,POINT (-8414880.114 696406.627),"(899, 1221)",175,175
1,110903600190000,13.0,"POLYGON ((-8415896.375 696427.477, -8415896.97...",110903600190000,POINT (-8415890.427 696432.566),"(135, 1180)",260,260
2,111103800030000,17.0,"POLYGON ((-8415918.661 697032.037, -8415918.94...",111103800030000,POINT (-8415919.432 697048.293),"(113, 200)",39,39
3,110500300270000,14.0,"POLYGON ((-8413918.398 695996.547, -8413918.30...",110500300270000,POINT (-8413920.912 695993.526),"(1625, 1879)",34,34
4,110505200240000,20.0,"POLYGON ((-8413990.066 696473.458, -8413993.32...",110505200240000,POINT (-8413993.085 696485.465),"(1571, 1096)",151,[151]
...,...,...,...,...,...,...,...,...
4901,110807500270000,11.0,"POLYGON ((-8415313.626 695932.177, -8415325.68...",110807500270000,POINT (-8415319.961 695940.346),"(566, 1964)",187,187
4902,110500400080000,12.0,"POLYGON ((-8414151.762 695957.224, -8414154.78...",110500400080000,POINT (-8414153.398 695962.394),"(1449, 1929)",34,34
4903,110503300130000,16.0,"POLYGON ((-8413574.983 696198.436, -8413572.37...",110503300130000,POINT (-8413577.268 696199.79),"(1885, 1551)",293,293
4904,111102300060000,17.0,"POLYGON ((-8415560.87 697056.44, -8415561.114 ...",111102300060000,POINT (-8415564.107 697063.954),"(382, 175)",56,56
4904,111102300060000,17.0,"POLYGON ((-8415568.403 697059.356, -8415568.84...",111102300060000,POINT (-8415568.776 697057.31),"(378, 185)",56,56

In [3]:
output_path = "./Cluster/mask_res/clustered_Cada.shp"
clustered_gdf.drop(columns=["centroid"]).to_file(output_path, driver="ESRI Shapefile",encoding = "utf-8")

INFO:pyogrio._io:Created 5,351 records

In [ ]:
# check the multipygons dealing